[[redirects]]
  from = "/LinkedIn"
  to = "www.linkedin.com/in/wchan1097"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"